--DROP TABLE NOTICE;
--DROP SEQUENCE SEQ_NOTICE_NO;
--SELECT * FROM (SELECT ROWNUM AS RNUM, B.* FROM (SELECT * FROM NOTICE ORDER BY DATE_CREATED DESC)B) WHERE RNUM BETWEEN 1 AND 5;
----게시판생성
CREATE TABLE NOTICE (   
   NOTICE_NO NUMBER,
   NOTICE_TITLE VARCHAR2(50),
   NOTICE_CONTENT VARCHAR2(2000), 
   DATE_CREATED DATE DEFAULT SYSDATE,
   DATE_MODIFIED DATE DEFAULT SYSDATE,
   NOTICE_READCOUNT NUMBER DEFAULT 0,
   CONSTRAINT PK_NOTICE_NO PRIMARY KEY(NOTICE_NO)
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '게시글번호';
COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '게시글제목';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '게시글내용';
COMMENT ON COLUMN "NOTICE"."DATE_CREATED" IS '게시글올린날짜';
COMMENT ON COLUMN "NOTICE"."DATE_MODIFIED" IS '게시글수정날짜';
COMMENT ON COLUMN "NOTICE"."NOTICE_READCOUNT" IS '조회수';

----게시판시퀀스생성
CREATE SEQUENCE SEQ_NOTICE_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;


Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 1','반갑습니다',to_date('18/01/11','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 1','반갑습니다',to_date('18/02/10','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 2','반갑습니다',to_date('18/02/12','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 3','반갑습니다',to_date('18/02/13','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 4','반갑습니다',to_date('18/02/14','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 5','반갑습니다',to_date('18/02/15','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 6','반갑습니다',to_date('18/02/16','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 7','반갑습니다',to_date('18/02/17','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 8','반갑습니다',to_date('18/02/18','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 9','반갑습니다',to_date('18/02/19','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 10','반갑습니다',to_date('18/02/20','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 11','반갑습니다',to_date('18/03/11','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 12','반갑습니다',to_date('18/03/12','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 13','반갑습니다',to_date('18/03/13','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 14','반갑습니다',to_date('18/03/14','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 15','반갑습니다',to_date('18/03/15','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 16','반갑습니다',to_date('18/03/16','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 17','반갑습니다',to_date('18/03/17','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 18','반갑습니다',to_date('18/03/18','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 19','반갑습니다',to_date('18/03/19','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 20','반갑습니다',to_date('18/03/20','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 21','반갑습니다',to_date('18/04/01','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 23','반갑습니다',to_date('18/04/03','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 24','반갑습니다',to_date('18/04/04','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 25','반갑습니다',to_date('18/04/05','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 26','반갑습니다',to_date('18/04/06','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 27','반갑습니다',to_date('18/04/07','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 28','반갑습니다',to_date('18/04/08','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 29','반갑습니다',to_date('18/04/09','RR/MM/DD'),0);
Insert into NOTICE (NOTICE_NO,NOTICE_TITLE,NOTICE_CONTENT,DATE_CREATED,NOTICE_READCOUNT) values (SEQ_NOTICE_NO.nextval,'안녕하세요, 게시판입니다 - 30','반갑습니다',to_date('18/04/10','RR/MM/DD'),0);

SELECT * FROM NOTICE;