SELECT * FROM QNA;

SELECT * FROM QNA_COMMENT;

SELECT * FROM MEMBER ;

--계층형쿼리 공부다시하기
--SELECT * FROM QNA_COMMENT WHERE QNA_REF=60
--START WITH QNA_COMMENT_LEVEL=1 CONNECT BY PRIOR QNA_COMMENT_NO=QNA_COMMENT_REF;

DROP TABLE QNA_COMMENT;

--SELECT * FROM QNA ORDER BY QNA_date DESC;

CREATE TABLE QNA_COMMENT(
    QNA_COMMENT_NO NUMBER PRIMARY KEY,
    QNA_COMMENT_LEVEL NUMBER DEFAULT 1,
    QNA_COMMENT_WRITER VARCHAR2(15), 
    QNA_COMMENT_CONTENT VARCHAR2(2000), 
    QNA_REF NUMBER, 
    QNA_COMMENT_REF NUMBER, 
    QNA_COMMENT_DATE DATE DEFAULT SYSDATE, 
--    CONSTRAINT PK_QNA_COMMENT_NO PRIMARY KEY(QNA_COMMENT_NO),
--    CONSTRAINT FK_QNA_COMMENT_WRITER FOREIGN KEY(QNA_COMMENT_WRITER) REFERENCES MEMBER(MEMBER_NAME) ON DELETE SET NULL,
    CONSTRAINT FK_QNA_REF FOREIGN KEY(QNA_REF) REFERENCES QNA(QUESTION_NO) ON DELETE CASCADE,
    CONSTRAINT FK_QNA_COMMENT_REF FOREIGN KEY(QNA_COMMENT_REF) REFERENCES QNA_COMMENT(QNA_COMMENT_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN QNA_COMMENT.QNA_COMMENT_NO IS 'QNA댓글번호';
COMMENT ON COLUMN QNA_COMMENT.QNA_COMMENT_LEVEL IS 'QNA댓글 레벨';
COMMENT ON COLUMN QNA_COMMENT.QNA_COMMENT_WRITER IS 'QNA댓글 작성자';
COMMENT ON COLUMN QNA_COMMENT.QNA_COMMENT_CONTENT IS 'QNA댓글';
COMMENT ON COLUMN QNA_COMMENT.QNA_REF IS '참조원글번호';
COMMENT ON COLUMN QNA_COMMENT.QNA_COMMENT_REF IS 'QNA댓글 참조번호';
COMMENT ON COLUMN QNA_COMMENT.QNA_COMMENT_DATE IS 'QNA댓글 작성일';

    
CREATE SEQUENCE SEQ_QNA_COMMENT_NO
START WITH 1
INCREMENT BY 1
NOMINVALUE
NOMAXVALUE
NOCYCLE
NOCACHE;

--테스트댓글 추가(qna가 있어야 댓글 가능)
INSERT INTO QNA_COMMENT VALUES(SEQ_QNA_COMMENT_NO.NEXTVAL, DEFAULT, 'admin','글 잘읽었습니다.',3,NULL,DEFAULT);
INSERT INTO QNA_COMMENT VALUES(SEQ_QNA_COMMENT_NO.NEXTVAL, DEFAULT, '유저01','좋은 정보 감사합니다.',61,NULL,DEFAULT);

--대댓글추가 : 댓글번호를 참조해서 insert할 것
INSERT INTO QNA_COMMENT VALUES(SEQ_QNA_COMMENT_NO.NEXTVAL, 2, 'stuv','좋은 정보가 어디에...?',61,30,DEFAULT);
INSERT INTO QNA_COMMENT VALUES(SEQ_QNA_COMMENT_NO.NEXTVAL, 2, 'efgh','하하하...안보이시는구나...',61,30,DEFAULT);
INSERT INTO QNA_COMMENT VALUES(SEQ_QNA_COMMENT_NO.NEXTVAL, 2, 'wxyz','얼씨구..',61,28,DEFAULT);
INSERT INTO QNA_COMMENT VALUES(SEQ_QNA_COMMENT_NO.NEXTVAL, 2, 'wxyz','저는 보입니다.',61,30,DEFAULT);
INSERT INTO QNA_COMMENT VALUES(SEQ_QNA_COMMENT_NO.NEXTVAL, 2, 'hijk','뭐임....',61,28,DEFAULT);
