ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER MYBATIS IDENTIFIED BY MYBATIS DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

SELECT * FROM DBA_USERS;

SELECT *
FROM DBA_USERS;

GRANT CONNECT, RESOURCE TO MYBATIS;

GRANT CREATE TABLE TO MYBATIS;

-- 생성 계정 접속
CREATE TABLE SCOTT_EN (
TEST VARCHAR2(200)
);

SELECT * FROM TAB;

SELECT *
FROM EMPLOYEE
--WHERE EMAIL LIKE '___%' ESCAPE '%' -- X
--WHERE EMAIL LIKE '___#_#_%' ESCAPE '#' -- '__'앞이 3개 글자인 이메일 찾기
WHERE EMAIL LIKE '___#_%' ESCAPE '#'
AND (DEPT_CODE ='D9' OR DEPT_CODE = 'D6')
AND HIRE_DATE BETWEEN '90/01/01' AND '00/12/01' -- (방식1)
--HIRE_DATE = '90/01/01' AND HIRE_DATE = '00/12/01' -- (방식2)
AND SALARY >= 2700000;